//Date : 11 sept 2024
///////////////////////////
// for website we need 
// HTMl for Structure,
// CSS for styling,
// Typescript / java script for add intraction or behaviour programitically interaction 
// THEN DEPLOY AT SERVER
// THEN WILL GET URL
// TO SEE THE ACTIVITY BETWEEN SERVER AND BROWSER ( GO TO INSPECT (DEV TOOL) ---> NETWORK )

//////////////////////////////////////////////
// SINGLE PAGE APPLICATION //
// WHEN WE PUT URL ON BROWSER ONLY FIRST REQUEST WILL GO TO SERVER AFTER THAT JAVASCRIPT WILL DO THE REST

// DOM (DOCUMENT OBJECT MODEL)
// IT PREPARE BY THE REPLY OF SERVER WHICH MAKE A DOCUMENT CALLED DOM WITH THE COMBINITION OF HTML, CSS AND JAVASCRIPT.

//"ANGULAR" BROUGHT BY GOOGLE TO SET STANDARDS OF SINGLE PAGE APPLICATION, THEN FACE BOOK BROUGHT "REACT" DUE TO SOME GLITCHES IN ANGULAR. 
// REACT BROUGHT //
// DECLARATIVE 
// COMPONENT ARCHITECTURE
// UNIDIRECTIONAL DATA FLOW
// UNILIBRARY

// ANGULAR WAS USING IMPARATIVE WAY INSTEAD OF DECLARATIVE WAY, IT WAS LIKE FROM ONE STATE TO OTHER STATE USED APROACH FOR TRANSECTIONING. THIS APPROACH WAS A FAILURE BY ANGULAR.

////////////////////////////////////////////////////
// DATE : 19 SEPT 2024
//////////////////////////////////////////////////

// server side rendering website
// client side rendering website
// server and client side rendering website ( different pages some server and some client)
// some component on one page of website are server side rendering and some are client side rendering





























